'use server';

/**
 * @fileOverview This file defines a Genkit flow for answering customer questions about their car or garage services.
 *
 * The flow takes a customer's question as input and returns an answer generated by the AI.
 * It uses a prompt that includes relevant context about the customer, their car, and the garage services.
 *
 * @interface AnswerCustomerQuestionsInput - The input type for the answerCustomerQuestions function.
 * @interface AnswerCustomerQuestionsOutput - The output type for the answerCustomerQuestions function.
 * @function answerCustomerQuestions - The main function that processes the customer's question and returns an answer.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerCustomerQuestionsInputSchema = z.object({
  question: z.string().describe('The question asked by the customer.'),
  customerName: z.string().describe('The name of the customer.'),
  vehicleInfo: z.string().describe('Information about the customer\'s vehicle (e.g., make, model, year).'),
  garageServices: z.string().describe('Information about the garage services offered.'),
});
export type AnswerCustomerQuestionsInput = z.infer<typeof AnswerCustomerQuestionsInputSchema>;

const AnswerCustomerQuestionsOutputSchema = z.object({
  answer: z.string().describe('The AI-generated answer to the customer\'s question.'),
});
export type AnswerCustomerQuestionsOutput = z.infer<typeof AnswerCustomerQuestionsOutputSchema>;

export async function answerCustomerQuestions(input: AnswerCustomerQuestionsInput): Promise<AnswerCustomerQuestionsOutput> {
  return answerCustomerQuestionsFlow(input);
}

const answerCustomerQuestionsPrompt = ai.definePrompt({
  name: 'answerCustomerQuestionsPrompt',
  input: {schema: AnswerCustomerQuestionsInputSchema},
  output: {schema: AnswerCustomerQuestionsOutputSchema},
  prompt: `You are a helpful AI assistant providing information to customers of a car garage.
  Use the following information to answer the customer's question:

  Customer Name: {{{customerName}}}
  Vehicle Info: {{{vehicleInfo}}}
  Garage Services: {{{garageServices}}}

  Question: {{{question}}}

  Answer:`,
});

const answerCustomerQuestionsFlow = ai.defineFlow(
  {
    name: 'answerCustomerQuestionsFlow',
    inputSchema: AnswerCustomerQuestionsInputSchema,
    outputSchema: AnswerCustomerQuestionsOutputSchema,
  },
  async input => {
    const {output} = await answerCustomerQuestionsPrompt(input);
    return output!;
  }
);
